name: say-hello

on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: make say-hello

      - uses: actions/hexlet-components/hello-from-hexlet-action
      - run: hexlet-components/hello-from-hexlet-action