name: say-hello

on: push
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - run: make say-hello

      - name: Run my Action
        id: run-action
        uses: actions/javascript-action@v1 # Commit with the `v1` tag
        with:
          milliseconds: 1000
      
      - name: Print Output
        id: output
        run: echo "${{ steps.run-action.outputs.time }}"